"""empty message

Revision ID: 7490b5e95fc6
Revises: 
Create Date: 2023-03-13 04:12:08.561338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7490b5e95fc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_caught',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Abilities', sa.String(), nullable=False),
    sa.Column('BaseExperience', sa.Integer(), nullable=False),
    sa.Column('FrontShinyURL', sa.String(), nullable=False),
    sa.Column('AttackBaseStat', sa.Integer(), nullable=False),
    sa.Column('HPBaseStat', sa.Integer(), nullable=False),
    sa.Column('DefenseBaseStat', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_team',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon_caught.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'pokemon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_team')
    op.drop_table('pokemon_caught')
    # ### end Alembic commands ###
